openapi: 3.0.1
info:
  description: Sample GIS Calc
  title: GIS Calc
  version: 0.1.0
servers:
- url: /
tags:
- description: GIS Calc
  name: giscalc
paths:
  /route_length:
    post:
      description: route length
      operationId: routeLength
      requestBody:
        $ref: '#/components/requestBodies/routeRequest'
        content:
          application/json:
            schema:
              properties:
                points:
                  items:
                    $ref: '#/components/schemas/point'
                  type: array
              required:
              - points
              title: routeRequest
              type: object
        description: route
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/routeLength'
          description: result
      tags:
      - giscalc
      x-eov-operation-handler: controllers/GiscalcController
components:
  requestBodies:
    routeRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/routeRequest'
      required: true
  schemas:
    point:
      properties:
        latitude:
          description: latitude
          type: number
        longitude:
          description: longitude
          type: number
      required:
      - latitude
      - longitude
      type: object
    route:
      items:
        $ref: '#/components/schemas/point'
      type: array
    routeRequest:
      properties:
        points:
          items:
            $ref: '#/components/schemas/point'
          type: array
      required:
      - points
      title: routeRequest
      type: object
    routeLength:
      example:
        length: 0.8008281904610115
      properties:
        length:
          type: number
      required:
      - length
      title: routeLength
      type: object
