/**
 * GIS Calc
 * Sample GIS Calc
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Point } from './point';

export class RouteRequest {
    'points': Array<Point>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "points",
            "baseName": "points",
            "type": "Array<Point>"
        }    ];

    static getAttributeTypeMap() {
        return RouteRequest.attributeTypeMap;
    }
}

